# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.api.turn_api import TurnApi  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestTurnApi(unittest.TestCase):
    """TurnApi unit test stubs"""

    def setUp(self):
        self.api = cyber_py_lib.api.turn_api.TurnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_unit_action(self):
        """Test case for create_unit_action

        Take an action as a unit on a turn.  # noqa: E501
        """
        pass

    def test_start_turn(self):
        """Test case for start_turn

        Start a turn  # noqa: E501
        """
        pass

    def test_update_turn(self):
        """Test case for update_turn

        Update a turn (used to end a turn)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
