# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.models.game_map import GameMap  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestGameMap(unittest.TestCase):
    """GameMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameMap(self):
        """Test GameMap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cyber_py_lib.models.game_map.GameMap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
