# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.api.lobby_api import LobbyApi  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestLobbyApi(unittest.TestCase):
    """LobbyApi unit test stubs"""

    def setUp(self):
        self.api = cyber_py_lib.api.lobby_api.LobbyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_player(self):
        """Test case for add_player

        Add a player to a game  # noqa: E501
        """
        pass

    def test_create_game(self):
        """Test case for create_game

        Create a game  # noqa: E501
        """
        pass

    def test_get_game(self):
        """Test case for get_game

        Get a specific game you know the ID for.  # noqa: E501
        """
        pass

    def test_get_maps(self):
        """Test case for get_maps

        Get all maps  # noqa: E501
        """
        pass

    def test_get_player(self):
        """Test case for get_player

        get a player by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
