# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.api.game_api import GameApi  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestGameApi(unittest.TestCase):
    """GameApi unit test stubs"""

    def setUp(self):
        self.api = cyber_py_lib.api.game_api.GameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_unit(self):
        """Test case for get_unit

        Get a specific unit  # noqa: E501
        """
        pass

    def test_get_units(self):
        """Test case for get_units

        Get units for a game.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
