# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.models.inline_object2 import InlineObject2  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestInlineObject2(unittest.TestCase):
    """InlineObject2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject2(self):
        """Test InlineObject2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cyber_py_lib.models.inline_object2.InlineObject2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
