# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cyber_py_lib
from cyber_py_lib.models.move_action_args import MoveActionArgs  # noqa: E501
from cyber_py_lib.rest import ApiException


class TestMoveActionArgs(unittest.TestCase):
    """MoveActionArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoveActionArgs(self):
        """Test MoveActionArgs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cyber_py_lib.models.move_action_args.MoveActionArgs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
