# coding: utf-8

"""
    Cyber Wars API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Map(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'number_of_players': 'int',
        'lobby_service': 'str'
    }

    attribute_map = {
        'id': 'id',
        'number_of_players': 'numberOfPlayers',
        'lobby_service': 'lobbyService'
    }

    def __init__(self, id=None, number_of_players=None, lobby_service=None):  # noqa: E501
        """Map - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._number_of_players = None
        self._lobby_service = None
        self.discriminator = None

        self.id = id
        self.number_of_players = number_of_players
        self.lobby_service = lobby_service

    @property
    def id(self):
        """Gets the id of this Map.  # noqa: E501


        :return: The id of this Map.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Map.


        :param id: The id of this Map.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def number_of_players(self):
        """Gets the number_of_players of this Map.  # noqa: E501


        :return: The number_of_players of this Map.  # noqa: E501
        :rtype: int
        """
        return self._number_of_players

    @number_of_players.setter
    def number_of_players(self, number_of_players):
        """Sets the number_of_players of this Map.


        :param number_of_players: The number_of_players of this Map.  # noqa: E501
        :type: int
        """
        if number_of_players is None:
            raise ValueError("Invalid value for `number_of_players`, must not be `None`")  # noqa: E501
        if number_of_players is not None and number_of_players < 1:  # noqa: E501
            raise ValueError("Invalid value for `number_of_players`, must be a value greater than or equal to `1`")  # noqa: E501

        self._number_of_players = number_of_players

    @property
    def lobby_service(self):
        """Gets the lobby_service of this Map.  # noqa: E501


        :return: The lobby_service of this Map.  # noqa: E501
        :rtype: str
        """
        return self._lobby_service

    @lobby_service.setter
    def lobby_service(self, lobby_service):
        """Sets the lobby_service of this Map.


        :param lobby_service: The lobby_service of this Map.  # noqa: E501
        :type: str
        """
        if lobby_service is None:
            raise ValueError("Invalid value for `lobby_service`, must not be `None`")  # noqa: E501

        self._lobby_service = lobby_service

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Map):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
